import { link } from "fs";

export default function Head() {
  return (
    <>
      <title>Form bueau d'ordre</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
